from enum import Enum

class CandidateState(str, Enum):
    REGISTERED = "REGISTERED"
    IN_ROUND = "IN_ROUND"
    ROUND_FAILED = "ROUND_FAILED"
    ASSESSMENT_COMPLETED = "ASSESSMENT_COMPLETED"
    DECISION_GENERATED = "DECISION_GENERATED"
    REVIEWED_BY_HR = "REVIEWED_BY_HR"
    REJECTED_PRE_ASSESSMENT = "REJECTED_PRE_ASSESSMENT"